services:
  - type: web
    name: kids-shop
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn kids.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: kids.settings
    staticPublishPath: staticfiles

staticPublishPaths:
  - path: /media
    source: media
